services:
  db_class_room:
    container_name: 'db_class_room'
    image: 'postgres:15'
    restart: always
    environment:
      POSTGRES_USER: class_room
      POSTGRES_PASSWORD: class_room
      POSTGRES_DB: class_room
    ports:
      - '5433:5432'
    volumes:
      - db_class_room:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db_class_room
    restart: always

volumes:
  db_class_room:
